const stockSymbolForPrice = {
    HDFCBank: "HDFCBANK.NS",
    BajajFinance: "BAJFINANCE.NS",
    ICICIBank: "ICICIBANK.BO",
    BajajHousing: "BAJAJHFL.BO",
    SavaniFinancials: "511577.BO",
    AffleIndia: "AFFLE.NS",
    LTIMindtree: "LTIM.NS",
    KPITTech: "KPITTECH.BO",
    TataTech: "TATATECH.BO",
    BLSEServices: "BLSE.BO",
    Tanla: "TANLA.BO",
    Dmart: "DMART.NS",
    TataConsumer: 'TATACONSUM.BO',
    Pidilite: 'PIDILITIND.BO',
    TataPower: "TATAPOWER.BO",
    KPIGreen: "KPIGREEN.BO",
    Suzlon: 'SUZLON.BO',
    Gensol: 'GENSOL.BO',
    HariomPipes: 'HARIOMPIPE.BO',
    Astral: 'ASTRAL.NS',
    Polycab: 'POLYCAB.BO',
    CleanScience: 'CLEAN.BO',
    DeepakNitrite: 'DEEPAKNTR.BO',
    FineOrganic: 'FINEORG.BO',
    Gravita: 'GRAVITA.BO',
    SBILife: 'SBILIFE.BO',
    Infy: 'INFY.BO',
    HappeistMind: 'HAPPSTMNDS.BO',
    Easemytrip: 'EASEMYTRIP.BO'
    }

const stockSymbolForStockData = {
    HDFCBank: "HDFCBANK:NSE",
    BajajFinance: "BAJFINANCE:NSE",
    ICICIBank: "532174:BOM",
    BajajHousing: "544252:BOM",
    SavaniFinancials: "511577:BOM",
    AffleIndia: "AFFLE:NSE",
    LTIMindtree: "LTIM:NSE",
    KPITTech: "542651:BOM",
    TataTech: "544028:BOM",
    BLSEServices: "BLSE:NSE",
    Tanla: "532790:BOM",
    Dmart: "DMART:NSE",
    TataConsumer: '532540:BOM',
    Pidilite: '500331:BOM',
    TataPower: '500400:BOM',
    KPIGreen: '542323:BOM',
    Suzlon: '532667:BOM',
    Gensol: '542851:BOM',
    HariomPipes: '543517:BOM',
    Astral: 'ASTRAL:NSE',
    Polycab: '542652:BOM',
    CleanScience: '543318:BOM',
    DeepakNitrite: '506401:BOM',
    FineOrganic: '541557:BOM',
    Gravita: '533282:BOM',
    SBILife: '540719:BOM',
    Infy: '500209:BOM',
    HappeistMind: '543237:BOM',
    Easemytrip: '543272:BOM'
    }
  

export const datas = [
    {
    particulars: "HDFC Bank",
    purchaseprice: 1490,
    quantity: 50,
    portfoliopercentage: "5%",
    nseorbse_for_yfinance: stockSymbolForPrice["HDFCBank"],
    nseorbse_for_puppet: stockSymbolForStockData["HDFCBank"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Bajaj Finance",
    purchaseprice: 6466,
    quantity: 15,
    portfoliopercentage: "6%",
    nseorbse_for_yfinance: stockSymbolForPrice["BajajFinance"],
    nseorbse_for_puppet: stockSymbolForStockData["BajajFinance"],
    latestearnings: "not accessible",
    },
    {
    particulars: "ICICI Bank",
    purchaseprice: 780,
    quantity: 84,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["ICICIBank"],
    nseorbse_for_puppet: stockSymbolForStockData["ICICIBank"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Bajaj Housing",
    purchaseprice: 130,
    quantity: 504,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["BajajHousing"],
    nseorbse_for_puppet: stockSymbolForStockData["BajajHousing"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Savani Financials",
    purchaseprice: 24,
    quantity: 1080,
    portfoliopercentage: "2%",
    nseorbse_for_yfinance: stockSymbolForPrice["SavaniFinancials"],
    nseorbse_for_puppet: stockSymbolForStockData["SavaniFinancials"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Affle India",
    purchaseprice: 1151,
    quantity: 50,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["AffleIndia"],
    nseorbse_for_puppet: stockSymbolForStockData["AffleIndia"],
    latestearnings: "not accessible",
    },
    {
    particulars: "LTI Mindtree",
    purchaseprice: 4775,
    quantity: 16,
    portfoliopercentage: "5%",
    nseorbse_for_yfinance: stockSymbolForPrice["LTIMindtree"],
    nseorbse_for_puppet: stockSymbolForStockData["LTIMindtree"],
    latestearnings: "not accessible",
    },
    {
    particulars: "KPIT Tech",
    purchaseprice: 672,
    quantity: 61,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["KPITTech"],
    nseorbse_for_puppet: stockSymbolForStockData["KPITTech"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Tata Tech",
    purchaseprice: 1072,
    quantity: 63,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["TataTech"],
    nseorbse_for_puppet: stockSymbolForStockData["TataTech"],
    latestearnings: "not accessible",
    },
    {
    particulars: "BLS E-Services",
    purchaseprice: 232,
    quantity: 191,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["BLSEServices"],
    nseorbse_for_puppet: stockSymbolForStockData["BLSEServices"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Tanls",
    purchaseprice: 1134,
    quantity: 45,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["Tanla"],
    nseorbse_for_puppet: stockSymbolForStockData["Tanla"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Dmart",
    purchaseprice: 3777,
    quantity: 27,
    portfoliopercentage: "7%",
    nseorbse_for_yfinance: stockSymbolForPrice["Dmart"],
    nseorbse_for_puppet: stockSymbolForStockData["Dmart"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Tata Consumer",
    purchaseprice: 845,
    quantity: 90,
    portfoliopercentage: "5%",
    nseorbse_for_yfinance: stockSymbolForPrice["TataConsumer"],
    nseorbse_for_puppet: stockSymbolForStockData["TataConsumer"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Pidilite",
    purchaseprice: 2376,
    quantity: 36,
    portfoliopercentage: "6%",
    nseorbse_for_yfinance: stockSymbolForPrice["Pidilite"],
    nseorbse_for_puppet: stockSymbolForStockData["Pidilite"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Tata Power",
    purchaseprice: 224,
    quantity: 225,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["TataPower"],
    nseorbse_for_puppet: stockSymbolForStockData["TataPower"],
    latestearnings: "not accessible",
    },
    {
    particulars: "KPI Green",
    purchaseprice: 875,
    quantity: 50,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["KPIGreen"],
    nseorbse_for_puppet: stockSymbolForStockData["KPIGreen"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Suzlon",
    purchaseprice: 44,
    quantity: 450,
    portfoliopercentage: "1%",
    nseorbse_for_yfinance: stockSymbolForPrice["Suzlon"],
    nseorbse_for_puppet: stockSymbolForStockData["Suzlon"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Gensol",
    purchaseprice: 998,
    quantity: 45,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["Gensol"],
    nseorbse_for_puppet: stockSymbolForStockData["Gensol"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Hariom Pipes",
    purchaseprice: 580,
    quantity: 60,
    portfoliopercentage: "2%",
    nseorbse_for_yfinance: stockSymbolForPrice["HariomPipes"],
    nseorbse_for_puppet: stockSymbolForStockData["HariomPipes"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Astral",
    purchaseprice: 1517,
    quantity: 56,
    portfoliopercentage: "6%",
    nseorbse_for_yfinance: stockSymbolForPrice["Astral"],
    nseorbse_for_puppet: stockSymbolForStockData["Astral"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Polycab",
    purchaseprice: 2818,
    quantity: 28,
    portfoliopercentage: "5%",
    nseorbse_for_yfinance: stockSymbolForPrice["Polycab"],
    nseorbse_for_puppet: stockSymbolForStockData["Polycab"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Clean Science",
    purchaseprice: 1610,
    quantity: 32,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["CleanScience"],
    nseorbse_for_puppet: stockSymbolForStockData["CleanScience"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Deepak Nitrite",
    purchaseprice: 2248,
    quantity: 27,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["DeepakNitrite"],
    nseorbse_for_puppet: stockSymbolForStockData["DeepakNitrite"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Fine Organic",
    purchaseprice: 4284,
    quantity: 16,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["FineOrganic"],
    nseorbse_for_puppet: stockSymbolForStockData["FineOrganic"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Gravita",
    purchaseprice: 2037,
    quantity: 8,
    portfoliopercentage: "1%",
    nseorbse_for_yfinance: stockSymbolForPrice["Gravita"],
    nseorbse_for_puppet: stockSymbolForStockData["Gravita"],
    latestearnings: "not accessible",
    },
    {
    particulars: "SBI Life",
    purchaseprice: 1197,
    quantity: 49,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["SBILife"],
    nseorbse_for_puppet: stockSymbolForStockData["SBILife"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Infy",
    purchaseprice: 1647,
    quantity: 36,
    portfoliopercentage: "4%",
    nseorbse_for_yfinance: stockSymbolForPrice["Infy"],
    nseorbse_for_puppet: stockSymbolForStockData["Infy"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Happeist Mind",
    purchaseprice: 1103,
    quantity: 45,
    portfoliopercentage: "3%",
    nseorbse_for_yfinance: stockSymbolForPrice["HappeistMind"],
    nseorbse_for_puppet: stockSymbolForStockData["HappeistMind"],
    latestearnings: "not accessible",
    },
    {
    particulars: "Easemytrip",
    purchaseprice: 20,
    quantity: 1332,
    portfoliopercentage: "2%",
    nseorbse_for_yfinance: stockSymbolForPrice["Easemytrip"],
    nseorbse_for_puppet: stockSymbolForStockData["Easemytrip"],
    latestearnings: "not accessible",
    },
    // ...
]

/*export const sector_wise_stocks = {
    financialSector : ["HDFC Bank", "Bajaj Finance", "ICICI Bank", "Bajaj Housing", "Savani Financials"],
    techSector: ["Affle India", "LTI Mindtree", "KPIT Tech", "Tata Tech", "BLS E-Services", "Tanla" ],
    consumer: ["Dmart", "Tata Consumer", "Pidilite"],
    power: ["Tata Power", "KPI Green", "Suzlon", "Gensol"],
    pipeSector: ["Hariom Pipes", "Astral", "Polycab"],
    others: ["Clean Science", "Deepak Nitrite", "Fine Organic","Gravita", "SBI Life"]
}*/

export const sector_wise_summary = [
    {
        name: "financialSector",
        stocksIncluded: ["HDFC Bank", "Bajaj Finance", "ICICI Bank", "Bajaj Housing", "Savani Financials"],
        investment: 20,
        presentValue: 60,
        gainorloss: 10
    },
    {
        name: "techSector",
        stocksIncluded: ["Affle India", "LTI Mindtree", "KPIT Tech", "Tata Tech", "BLS E-Services", "Tanla" ],
        investment: 30,
        presentValue: 50,
        gainorloss: 20
    },
    {
        name: "consumer",
        stocksIncluded: ["Dmart", "Tata Consumer", "Pidilite"],
        investment: 40,
        presentValue: 40,
        gainorloss: 0
    },
    {
        name: "power",
        stocksIncluded: ["Tata Power", "KPI Green", "Suzlon", "Gensol"],
        investment: 50,
        presentValue: 30,
        gainorloss: 0
    },
    {
        name: "pipeSector",
        stocksIncluded: ["Hariom Pipes", "Astral", "Polycab"],
        investment: 60,
        presentValue: 20,
        gainorloss: 20
    },
    {
        name: "others",
        stocksIncluded: ["Clean Science", "Deepak Nitrite", "Fine Organic","Gravita", "SBI Life", "Infy", "Happeist Mind", "Easemytrip"],
        investment: 70,
        presentValue: 10,
        gainorloss: 10
    }
]


